#!/usr/bin/env ruby
require 'optparse'
require_relative "../lib/convert2ascii/image2ascii"


options = {}
OptionParser.new do |parser|
  parser.banner = "Usage: image2ascii [options]"

  parser.on("--version", "version") do |v|
    puts "convert2ascii/image2ascii: v#{::Convert2Ascii::VERSION}"
    puts "author: Mark24"
    puts "mail: mark.zhangyoung@gmail.com"
    puts "project: https://github.com/mark24Code/convert2ascii"
    return
  end

  parser.on("-iURI", "--image=URI", "image uri (required)") do |uri|
    options[:uri] = uri

    # check options
    unless options[:uri]
      puts "Error: --image option is required."
      exit 1
    end
  end

  parser.on("-wWIDTH", "--width=WIDTH", Integer ,"image width (integer)") do |width|
    options[:width] = width
  end

  parser.on("-sSTYLE", "--style=STYLE", "ascii style: ['color'| 'text']") do |style|
    options[:style] = style

    styles = ["color", "text"]
    # check options
    unless styles.include? options[:style]
      puts "Error: --style option must be [\"color\" | \"text\"]."
      exit 1
    end
  end

  parser.on("-b", "--block", "ascii color style use BLOCK or not [ true | false ] ") do |color_block|
    options[:color_block] = color_block || false
  end
end.parse!

Convert2Ascii::Image2Ascii.new(**options).generate.tty_print
